import { books, clothes, elect, kitchen, pic1, pic2, pic3, sports } from "@/assets"


export const data = [
    {
        asin:"B0CWHXVLXG",
product_title:"Moto G 5G | 2024 | Unlocked | Made for US 4/128GB | 50MP Camera | Sage Green",
product_price:"$149.99",
product_original_price:"$199.99",
currency:"USD",
product_star_rating:"4.2",
product_num_ratings:1395,
product_url:"https://www.amazon.com/dp/B0CWHXVLXG",
product_photo:"https://m.media-amazon.com/images/I/71Sbx9zQN3L._AC_UY654_FMwebp_QL65_.jpg",
product_num_offers:3,
product_minimum_offer_price:"$109.80",
is_best_seller:false,
is_amazon_choice:false,
is_prime:true,
climate_pledge_friendly:false,
sales_volume:"3K+ bought in past month",
delivery:"FREE delivery Sun, Jan 26 Or fastest delivery Tomorrow, Jan 22",
has_variations:true,
    },
    {
        asin:"B0CTW8TXGH",
product_title:"Tracfone | Motorola Moto g Play 2024 | Locked | 64GB | 5000mAh Battery | 50MP Quad Pixel Camera | 6.5-in. HD+ 90Hz Display | Sapphire Blue",
product_price:"$39.88",
product_original_price:"$49.99",
currency:"USD",
product_star_rating:"4.4",
product_num_ratings:236,
product_url:"https://www.amazon.com/dp/B0CTW8TXGH",
product_photo:"https://m.media-amazon.com/images/I/71CxUvG46rL._AC_UY654_FMwebp_QL65_.jpg",
product_num_offers:1,
product_minimum_offer_price:"$39.88",
is_best_seller:false,
is_amazon_choice:false,
is_prime:true,
climate_pledge_friendly:false,
sales_volume:"3K+ bought in past month",
delivery:"FREE delivery Sun, Jan 26 Or fastest delivery Tomorrow, Jan 22",
has_variations:false,
    },
    {
        asin:"B0DHSV6LCN",
product_title:"Samsung Galaxy Z Flip 6 AI Cell Phone, 512GB Unlocked Android Smartphone - (Renewed) (Blue, 512GB) (Blue)",
product_price:"$939.00",
product_original_price:null,
currency:"USD",
product_star_rating:"3.9",
product_num_ratings:5,
product_url:"https://www.amazon.com/dp/B0DHSV6LCN",
product_photo:"https://m.media-amazon.com/images/I/51mRtvBdsqL._AC_UY654_FMwebp_QL65_.jpg",
product_num_offers:1,
product_minimum_offer_price:"$939.00",
is_best_seller:false,
is_amazon_choice:false,
is_prime:false,
climate_pledge_friendly:false,
sales_volume:null,
delivery:"FREE delivery",
has_variations:true,
    },
    {
        asin:"B0CSB22F9C",
product_title:"Samsung Galaxy A15 (SM-155M/DSN), 128GB 6GB RAM, Dual SIM, Factory Unlocked GSM, International Version (Wall Charger Bundle) (Light Blue)",
product_price:"$149.99",
product_original_price:"$167.00",
currency:"USD",
product_star_rating:"4.2",
product_num_ratings:1424,
product_url:"https://www.amazon.com/dp/B0CSB22F9C",
product_photo:"https://m.media-amazon.com/images/I/31bNhi6E3eL._AC_UY650_FMwebp_QL65_.jpg",
product_num_offers:12,
product_minimum_offer_price:"$139.95",
is_best_seller:false,
is_amazon_choice:false,
is_prime:false,
climate_pledge_friendly:false,
sales_volume:"4K+ bought in past month",
delivery:"FREE delivery",
has_variations:false,
    },
]

export const pics = [
    {
        id: 1,
        img: pic1,
    },
    {
        id: 2,
        img: pic2,
    },
    {
        id: 3,
        img: pic3,
    },
]


export const categoriesData = [
    {id: 1, title: 'electronics', img: elect},
    {id: 2, title: 'kitchen', img: kitchen},
    {id: 3, title: 'books', img: books},
    {id: 4, title: 'sports', img: sports},
    {id: 5, title: 'clothes', img: clothes},
]